# Generated by Django 4.2.3 on 2023-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietas_app", "0005_alter_alimento_peso_alter_alimento_proteina_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medida",
            name="classificacao",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Classificação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medida",
            name="imc",
            field=models.DecimalField(
                decimal_places=3, default=1, max_digits=15, verbose_name="Imc"
            ),
            preserve_default=False,
        ),
    ]
